---
collections:
- name: community.general
  source: https://galaxy.ansible.com

- name: containers.podman
  source: https://galaxy.ansible.com

- name: 'petermosmans.customize-gnome'
  source: https://galaxy.ansible.com
