---
# tasks file for github
- name: add github-cli repository
  yum_repository:
    name: github-cli
    description: github cli repository
    baseurl: https://cli.github.com/packages/rpm
    enabled: yes

- name: install github cli
  dnf:
    name: gh
    state: present