---
- name: Install vscode
  flatpak:
    name: 'com.visualstudio.code'
    state: present
    method: user

- name: add vscode rpm key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add vscode repositories 
  yum_repository:
    name: vscode
    description: vscode repo
    file: vscode_repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Install vscode
  yum:
    name: 'code'
    state: present
