---
# tasks file for gsettings

- name: Add japanese language to keyboard for gnome
  ansible.builtin.command:
    cmd: gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('ibus', 'anthy')]"
  changed_when: false
  become: false
