---
# Called in templates/vfio-modprobe.conf.j2
ids_to_pass: '{{ vfio_pci_ids|join(",") }}'

# ansible_processor is a list (!) set up like:
# [ core number, vendor, model, core number, vendor, model, ... ]
cpu_vendor: "{{ ansible_facts['processor'][1] | lower | regex_replace('(authentic)|(genuine)', '') }}"
iommu_kernel_cmds: '{{ cpu_vendor }}_iommu=on iommu=pt rd.driver.pre=vfio-pci'
