---
# tasks file for nvidia
- name: Install nvidia proprietary drivers from rpm fusion
  ansible.builtin.yum:
    name: 
      - 'akmod-nvidia'
      - 'xorg-x11-drv-nvidia-cuda'
    state: present

- name: Blacklist the nouveau driver module
  community.general.kernel_blacklist:
    name: nouveau
    state: present