---
# tasks file for yubi_u2f

- name: Install yubi utils
  yum:
    name: 
      -  'pamu2fcfg'
      -  'pam-u2f'
    state: present

- name: Check that the yubi mappings file exists
  stat:
    path: /etc/yubikey_mappings
  register: stat_result

- name: Create the yubikey_mappings file, if it doesn't exist already
  file:
    path: /etc/yubikey_mappings
    state: touch
  when: not stat_result.stat.exists

- name: create pam.d rule
  pamd:
    name: gdm-password
    type: auth
    control: required
    module_path: pam_u2f.so
    new_control: sufficient
    module_arguments: 'authfile=/etc/yubikey_mappings'
    backup: 'yes'