---
- name: Add the flathub community.general.flatpak repository remote to the user installation
  ansible.builtin.shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    
- name: Install signal, telegram, zoom, githubcli bluejeans and discord in a loop
  community.general.flatpak:
    name: 
      - org.signal.Signal
      - org.telegram.desktop
      - us.zoom.Zoom
      - io.github.shiftey.Desktop
      - com.bluejeans.BlueJeans
      - com.discordapp.Discord
      - org.chromium.Chromium
    state: present