---
- name: Add the flathub community.general.flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.community.general.flatpakrepo
    
- name: Install Signal community.general.flatpak
  community.general.flatpak:
    name: org.signal.Signal
    state: present

- name: Install Slack community.general.flatpak
  community.general.flatpak:
    name: com.slack.Slack
    state: present

- name: Install Zoom community.general.flatpak
  community.general.flatpak:
    name: us.zoom.Zoom
    state: present

- name: Install Github Desktop community.general.flatpak
  community.general.flatpak:
    name: io.github.shiftey.Desktop
    state: present

- name: Install BlueJeans Desktop community.general.flatpak
  community.general.flatpak:
    name: com.bluejeans.BlueJeans
    state: present

- name: Install Discord
  community.general.flatpak:
    name: com.discordapp.Discord
    state: present