---
- name: Generate grub config
  ansible.builtin.command:
    cmd: grub2-mkconfig -o /boot/efi/EFI/{{ ansible_facts['distribution'] | lower }}/grub.cfg
  changed_when: false

- name: Rebuild initrd
  ansible.builtin.command:
    cmd: dracut -f
  changed_when: false

- name: Reboot
  ansible.builtin.reboot:
  when: auto_reboot
