---
- name: Get openshift client
  ansible.builtin.get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/oc/latest/linux/oc.tar.gz
    dest: /tmp/oc.tar.gz

- name: Check that the yubi mappings file exists
  ansible.builtin.stat:
    path: /usr/bin/oc
  register: stat_result

- name: Untar openshift client
  ansible.builtin.unarchive:
    src: /tmp/oc.tar.gz
    dest: /usr/bin/
    mode: "0644"
  when: not stat_result.stat.exists
