---
- name: get openshift client
  ansible.builtin.get_url:
    url='https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/oc/latest/linux/oc.tar.gz'
    dest='/tmp/oc.tar.gz'

- name: untar openshift client
  ansible.builtin.unarchive:
    src: '/tmp/oc.tar.gz'
    dest: '/usr/bin/'
