---
- name: Configure Fedora Workstation
  hosts: all
  gather_facts: True
  become: True
  roles:
    - role: petermosmans.customize-gnome
  vars:
    gnome_extensions:
      - id: 307
        enable: yes