---
- name: Configure Fedora Workstation
  hosts: localhost
  become: true
  vars:
    gnome_extensions:
      - id: 307
        enable: true
  gather_facts: true
  roles:
    - role: petermosmans.customize-gnome
