---
- name: Install conky and other prerequisites 
  ansible.builtin.yum:
    name: 
      -  'conky'
      -  'vim-common'
      -  'redhat-lsb-core'

- name: copy conky config file
  ansible.builtin.copy:
    src: files/conky.conf
    dest: '/etc/conky/conky.conf'
    owner: 'root'
    group: 'root'
    mode: 0644
